const actionType = {
  GET_ALL_DATA_REQUEST: 'GET_ALL_DATA_REQUEST',
  GET_ALL_DATA_SUCCESS: 'GET_ALL_DATA_SUCCESS',
  GET_ALL_DATA_ERROR: 'GET_ALL_DATA_ERROR',
  UPDATE_DATA_REQUEST: 'UPDATE_DATA_REQUEST',
  UPDATE_DATA_SUCCESS: 'UPDATE_DATA_SUCCESS',
  UPDATE_DATA_ERROR: 'UPDATE_DATA_ERROR',
  UPDATE_DATA_RESET: 'UPDATE_DATA_RESET',
  DELETE_DATA_REQUEST: 'DELETE_DATA_REQUEST',
  DELETE_DATA_SUCCESS: 'DELETE_DATA_SUCCESS',
  DELETE_DATA_ERROR: 'DELETE_DATA_ERROR',

  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',
  USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
  USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  USER_LOGOUT_ERROR: 'USER_LOGOUT_ERROR',
};

export default actionType;
